//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.Users {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtCnName;
		protected global::System.Web.UI.WebControls.TextBox txtLoginName;
		protected global::System.Web.UI.WebControls.TextBox txtLoginPwd;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtUserRoleId;
		protected global::System.Web.UI.WebControls.TextBox txtUserStateId;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDel;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
