//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.RouteDatas {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtReportWeek;
		protected global::System.Web.UI.WebControls.TextBox txtReportYear;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtRouteId;
		protected global::System.Web.UI.WebControls.TextBox txtLineId;
		protected global::System.Web.UI.WebControls.TextBox txtGP20;
		protected global::System.Web.UI.WebControls.TextBox txtGP40;
		protected global::System.Web.UI.WebControls.TextBox txtHQ40;
		protected global::System.Web.UI.WebControls.TextBox txtHQ45;
		protected global::System.Web.UI.WebControls.TextBox txtTEU;
		protected global::System.Web.UI.WebControls.TextBox txtOthers;
		protected global::System.Web.UI.WebControls.CheckBox chkIsReported;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.TextBox txtEditTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
