//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.RouteDatas {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblReportWeek;
	protected global::System.Web.UI.WebControls.Label lblReportYear;
	protected global::System.Web.UI.WebControls.Label lblCompanyId;
	protected global::System.Web.UI.WebControls.Label lblRouteId;
	protected global::System.Web.UI.WebControls.Label lblLineId;
	protected global::System.Web.UI.WebControls.Label lblGP20;
	protected global::System.Web.UI.WebControls.Label lblGP40;
	protected global::System.Web.UI.WebControls.Label lblHQ40;
	protected global::System.Web.UI.WebControls.Label lblHQ45;
	protected global::System.Web.UI.WebControls.Label lblTEU;
	protected global::System.Web.UI.WebControls.Label lblOthers;
	protected global::System.Web.UI.WebControls.Label lblIsReported;
	protected global::System.Web.UI.WebControls.Label lblAddTime;
	protected global::System.Web.UI.WebControls.Label lblEditTime;


       
    }
}
