//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.DeclareDatas {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtDeclareReportWeek;
		protected global::System.Web.UI.WebControls.TextBox txtDeclareReportYear;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtGFOuterDeclareBallot;
		protected global::System.Web.UI.WebControls.TextBox txtGFSelfDeclareBallot;
		protected global::System.Web.UI.WebControls.TextBox txtGFOtherDeclareBallot;
		protected global::System.Web.UI.WebControls.TextBox txtQTOuterDeclareBallot;
		protected global::System.Web.UI.WebControls.TextBox txtQTSelfDeclareBallot;
		protected global::System.Web.UI.WebControls.TextBox txtQTOtherDeclareBallot;
		protected global::System.Web.UI.WebControls.TextBox txtGFOuterDeclareContainer;
		protected global::System.Web.UI.WebControls.TextBox txtGFSelfDeclareContainer;
		protected global::System.Web.UI.WebControls.TextBox txtGFOtherDeclareContainer;
		protected global::System.Web.UI.WebControls.TextBox txtQTOuterDeclareContainer;
		protected global::System.Web.UI.WebControls.TextBox txtQTSelfDeclareContainer;
		protected global::System.Web.UI.WebControls.TextBox txtQTOtherDeclareContainer;
		protected global::System.Web.UI.WebControls.TextBox txtGFOuterDeclareIncome;
		protected global::System.Web.UI.WebControls.TextBox txtGFSelfDeclareIncome;
		protected global::System.Web.UI.WebControls.TextBox txtGFOtherDeclareIncome;
		protected global::System.Web.UI.WebControls.TextBox txtQTOuterDeclareIncome;
		protected global::System.Web.UI.WebControls.TextBox txtQTSelfDeclareIncome;
		protected global::System.Web.UI.WebControls.TextBox txtQTOtherDeclareIncome;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.TextBox txtEditTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsReported;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
