//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.DeclareDatas {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDeclareReportWeek;
	protected global::System.Web.UI.WebControls.Label lblDeclareReportYear;
	protected global::System.Web.UI.WebControls.Label lblCompanyId;
	protected global::System.Web.UI.WebControls.Label lblGFOuterDeclareBallot;
	protected global::System.Web.UI.WebControls.Label lblGFSelfDeclareBallot;
	protected global::System.Web.UI.WebControls.Label lblGFOtherDeclareBallot;
	protected global::System.Web.UI.WebControls.Label lblQTOuterDeclareBallot;
	protected global::System.Web.UI.WebControls.Label lblQTSelfDeclareBallot;
	protected global::System.Web.UI.WebControls.Label lblQTOtherDeclareBallot;
	protected global::System.Web.UI.WebControls.Label lblGFOuterDeclareContainer;
	protected global::System.Web.UI.WebControls.Label lblGFSelfDeclareContainer;
	protected global::System.Web.UI.WebControls.Label lblGFOtherDeclareContainer;
	protected global::System.Web.UI.WebControls.Label lblQTOuterDeclareContainer;
	protected global::System.Web.UI.WebControls.Label lblQTSelfDeclareContainer;
	protected global::System.Web.UI.WebControls.Label lblQTOtherDeclareContainer;
	protected global::System.Web.UI.WebControls.Label lblGFOuterDeclareIncome;
	protected global::System.Web.UI.WebControls.Label lblGFSelfDeclareIncome;
	protected global::System.Web.UI.WebControls.Label lblGFOtherDeclareIncome;
	protected global::System.Web.UI.WebControls.Label lblQTOuterDeclareIncome;
	protected global::System.Web.UI.WebControls.Label lblQTSelfDeclareIncome;
	protected global::System.Web.UI.WebControls.Label lblQTOtherDeclareIncome;
	protected global::System.Web.UI.WebControls.Label lblAddTime;
	protected global::System.Web.UI.WebControls.Label lblEditTime;
	protected global::System.Web.UI.WebControls.Label lblIsReported;


       
    }
}
