//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.LinerDatas {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtReportWeek;
		protected global::System.Web.UI.WebControls.TextBox txtReportYear;
		protected global::System.Web.UI.WebControls.TextBox txtLinerCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtProxyShipCount;
		protected global::System.Web.UI.WebControls.TextBox txtProxyContainerCount;
		protected global::System.Web.UI.WebControls.CheckBox chkIsReported;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.TextBox txtEditTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
