//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.LinerDatas {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblCompanyId;
	protected global::System.Web.UI.WebControls.Label lblReportWeek;
	protected global::System.Web.UI.WebControls.Label lblReportYear;
	protected global::System.Web.UI.WebControls.Label lblLinerCompanyId;
	protected global::System.Web.UI.WebControls.Label lblProxyShipCount;
	protected global::System.Web.UI.WebControls.Label lblProxyContainerCount;
	protected global::System.Web.UI.WebControls.Label lblIsReported;
	protected global::System.Web.UI.WebControls.Label lblAddTime;
	protected global::System.Web.UI.WebControls.Label lblEditTime;


       
    }
}
