//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSADataReport.Web.Companies {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtId;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyName;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyCode;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyNum;
		protected global::System.Web.UI.WebControls.TextBox txtAreaId;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyTypeId;
		protected global::System.Web.UI.WebControls.TextBox txtParentCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDel;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
